services:
  replacecompositekey:
    image: replacecompositekey
    build:
      context: .
      dockerfile: ReplaceCompositeKey/Dockerfile
    depends_on:
      - postgres
  
  postgres:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydatabase