// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using ReplaceCompositeKey;

#nullable disable

namespace ReplaceCompositeKey.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20241217113831_InitialMigration")]
    partial class InitialMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ReplaceCompositeKey.MyEntity", b =>
                {
                    b.Property<string>("Prop1")
                        .HasColumnType("text");

                    b.Property<string>("Prop2")
                        .HasColumnType("text");

                    b.Property<string>("OtherProp")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Prop1", "Prop2");

                    b.ToTable("Entities");

                    b.HasData(
                        new
                        {
                            Prop1 = "q3vne2kr",
                            Prop2 = "3cmcj7sm",
                            OtherProp = "Qui inventore cumque explicabo ut atque sapiente aut modi."
                        },
                        new
                        {
                            Prop1 = "qo9evps4",
                            Prop2 = "zrtusf2o",
                            OtherProp = "In accusantium voluptate eius explicabo suscipit sint soluta perferendis."
                        },
                        new
                        {
                            Prop1 = "kup2fxjo",
                            Prop2 = "qsgdl85x",
                            OtherProp = "Corporis at ullam vel explicabo consectetur exercitationem dolor."
                        },
                        new
                        {
                            Prop1 = "9dhncewv",
                            Prop2 = "5wnym3ki",
                            OtherProp = "Quis incidunt non ipsam sit."
                        },
                        new
                        {
                            Prop1 = "p6ponwmc",
                            Prop2 = "jtekdzbo",
                            OtherProp = "Voluptas cumque aut at repudiandae voluptas sed."
                        },
                        new
                        {
                            Prop1 = "slee3mvu",
                            Prop2 = "klxeg3fi",
                            OtherProp = "Molestiae autem nam maiores fuga magni veritatis et sit."
                        },
                        new
                        {
                            Prop1 = "4teqw57o",
                            Prop2 = "zcq1o30c",
                            OtherProp = "Consequatur qui provident impedit."
                        },
                        new
                        {
                            Prop1 = "ktw1foqz",
                            Prop2 = "zndnnebf",
                            OtherProp = "Expedita quis molestiae voluptate molestiae."
                        },
                        new
                        {
                            Prop1 = "6wcqd1yi",
                            Prop2 = "ebhwcnua",
                            OtherProp = "Et autem quis voluptas voluptas nisi minus est."
                        },
                        new
                        {
                            Prop1 = "lxj8p30w",
                            Prop2 = "pou1llp5",
                            OtherProp = "Praesentium dolores est qui dolorum ut sequi accusamus temporibus voluptatem."
                        },
                        new
                        {
                            Prop1 = "yyh4bvtf",
                            Prop2 = "w6cejot7",
                            OtherProp = "Qui perferendis quo odio."
                        },
                        new
                        {
                            Prop1 = "98uxl937",
                            Prop2 = "5825qd6m",
                            OtherProp = "Ad voluptatem at."
                        },
                        new
                        {
                            Prop1 = "989ckcyo",
                            Prop2 = "z4n8k5zc",
                            OtherProp = "Similique in dolor aut ut et maiores autem sit est."
                        },
                        new
                        {
                            Prop1 = "53bitdbx",
                            Prop2 = "09j6obqd",
                            OtherProp = "Ut magni ut culpa vero quia harum."
                        },
                        new
                        {
                            Prop1 = "ublorxbt",
                            Prop2 = "h3dx0ykb",
                            OtherProp = "Corrupti maxime delectus cumque iure illo quod asperiores."
                        },
                        new
                        {
                            Prop1 = "mq7m1rgd",
                            Prop2 = "zrzvg64n",
                            OtherProp = "Rerum et harum delectus at molestias mollitia nulla est."
                        },
                        new
                        {
                            Prop1 = "65upkvme",
                            Prop2 = "2rv90kbd",
                            OtherProp = "Deleniti vero reprehenderit nemo reprehenderit inventore quia praesentium et."
                        },
                        new
                        {
                            Prop1 = "yms8nmon",
                            Prop2 = "usqmmtod",
                            OtherProp = "Exercitationem et dolores illo odio magni."
                        },
                        new
                        {
                            Prop1 = "5k8b928t",
                            Prop2 = "5tm3qkry",
                            OtherProp = "Ex quia atque aut ducimus facilis."
                        },
                        new
                        {
                            Prop1 = "ml6bgcrn",
                            Prop2 = "fjlvalom",
                            OtherProp = "Velit nisi dignissimos."
                        },
                        new
                        {
                            Prop1 = "wtrobuva",
                            Prop2 = "plupm89k",
                            OtherProp = "Veritatis vel quo quibusdam id quia."
                        },
                        new
                        {
                            Prop1 = "inpinp91",
                            Prop2 = "ztn205x0",
                            OtherProp = "Velit vel veritatis doloribus nisi."
                        },
                        new
                        {
                            Prop1 = "7uocz4u7",
                            Prop2 = "eand82pd",
                            OtherProp = "Aut et dolor ducimus."
                        },
                        new
                        {
                            Prop1 = "q3w3nmre",
                            Prop2 = "dhoutsim",
                            OtherProp = "Quia perferendis eos blanditiis."
                        },
                        new
                        {
                            Prop1 = "rf3kxaz4",
                            Prop2 = "1yicxtws",
                            OtherProp = "Velit dolorum voluptates sunt aliquam fuga velit culpa maxime."
                        },
                        new
                        {
                            Prop1 = "5ewses0w",
                            Prop2 = "vh289svd",
                            OtherProp = "Placeat aut sit animi veniam sint."
                        },
                        new
                        {
                            Prop1 = "95vqvwpj",
                            Prop2 = "bueb21mb",
                            OtherProp = "Quibusdam sint officiis."
                        },
                        new
                        {
                            Prop1 = "9l761pix",
                            Prop2 = "06mibxbv",
                            OtherProp = "Explicabo sunt hic eos aut pariatur."
                        },
                        new
                        {
                            Prop1 = "8cbzzg19",
                            Prop2 = "zs7sg03u",
                            OtherProp = "Vel autem et et aut aut."
                        },
                        new
                        {
                            Prop1 = "l6op9bdv",
                            Prop2 = "zkzj7ezp",
                            OtherProp = "Maiores odio laudantium suscipit facilis atque accusantium dolorem tempore."
                        },
                        new
                        {
                            Prop1 = "hojw1ts9",
                            Prop2 = "2lvw1vo2",
                            OtherProp = "Minima ipsa minima repellendus quae soluta dolorem sunt aut quasi."
                        },
                        new
                        {
                            Prop1 = "u8qpmf9c",
                            Prop2 = "wz60m05z",
                            OtherProp = "Dolorem dolorem rerum omnis asperiores qui rem totam in."
                        },
                        new
                        {
                            Prop1 = "mrezxsri",
                            Prop2 = "5hd788p7",
                            OtherProp = "Dicta corporis et voluptatem possimus quasi."
                        },
                        new
                        {
                            Prop1 = "r9ljigki",
                            Prop2 = "5vgoilgq",
                            OtherProp = "Quo vel et quia esse at."
                        },
                        new
                        {
                            Prop1 = "ejjd5u3h",
                            Prop2 = "vio0a6ca",
                            OtherProp = "Officiis dicta esse alias tenetur ex laborum animi."
                        },
                        new
                        {
                            Prop1 = "kvty95nz",
                            Prop2 = "mae4147w",
                            OtherProp = "Doloribus consequatur a sit quo et."
                        },
                        new
                        {
                            Prop1 = "hkxy899d",
                            Prop2 = "w6akzbe3",
                            OtherProp = "Cupiditate autem consequatur quos perferendis dicta est rerum dicta et."
                        },
                        new
                        {
                            Prop1 = "llo7gejk",
                            Prop2 = "1pxh9xpi",
                            OtherProp = "Eligendi nihil similique."
                        },
                        new
                        {
                            Prop1 = "av9pv40r",
                            Prop2 = "800m820m",
                            OtherProp = "Aperiam laboriosam enim a."
                        },
                        new
                        {
                            Prop1 = "zrwxkv0i",
                            Prop2 = "2wwh9syt",
                            OtherProp = "Commodi et quis culpa."
                        },
                        new
                        {
                            Prop1 = "rr7yb4pj",
                            Prop2 = "7wkjk9wf",
                            OtherProp = "Quos sint repellendus iste qui odio ad culpa eius."
                        },
                        new
                        {
                            Prop1 = "cgr3tpuw",
                            Prop2 = "eauw1j0u",
                            OtherProp = "Voluptas laudantium aperiam."
                        },
                        new
                        {
                            Prop1 = "6n9ncoog",
                            Prop2 = "5a3qjdrf",
                            OtherProp = "Vel id suscipit harum aut sint quasi ipsum eius pariatur."
                        },
                        new
                        {
                            Prop1 = "vbv00azk",
                            Prop2 = "d4rsn5at",
                            OtherProp = "Magni voluptatibus quia."
                        },
                        new
                        {
                            Prop1 = "8076b39n",
                            Prop2 = "0lqhz9sa",
                            OtherProp = "Sed dolore doloribus quibusdam laborum quibusdam aperiam quia."
                        },
                        new
                        {
                            Prop1 = "73rsauu1",
                            Prop2 = "4pda3qr1",
                            OtherProp = "Natus eum minus reiciendis."
                        },
                        new
                        {
                            Prop1 = "p9cghgev",
                            Prop2 = "rxy1jqzw",
                            OtherProp = "Sequi repudiandae nihil dolorem rem nam."
                        },
                        new
                        {
                            Prop1 = "j860w4g4",
                            Prop2 = "cmapkugk",
                            OtherProp = "Laboriosam quo asperiores dolorum vel ut quod."
                        },
                        new
                        {
                            Prop1 = "wf1erreq",
                            Prop2 = "jxea5uwg",
                            OtherProp = "Hic suscipit consequatur facilis amet omnis."
                        },
                        new
                        {
                            Prop1 = "lrc6jgay",
                            Prop2 = "ty6k75xr",
                            OtherProp = "Magnam ad eaque vel a labore delectus vel."
                        },
                        new
                        {
                            Prop1 = "8mmpfnta",
                            Prop2 = "c2rujn7h",
                            OtherProp = "Id earum deleniti qui consequatur quos voluptates fugit saepe."
                        },
                        new
                        {
                            Prop1 = "ua11hokd",
                            Prop2 = "87xer607",
                            OtherProp = "Autem ex odio saepe a vitae voluptas recusandae."
                        },
                        new
                        {
                            Prop1 = "8tu1bfsb",
                            Prop2 = "y2nf9xtf",
                            OtherProp = "Aperiam vel laboriosam rerum."
                        },
                        new
                        {
                            Prop1 = "78947am8",
                            Prop2 = "l26z4y8s",
                            OtherProp = "Neque natus nulla temporibus placeat quo maiores ea nostrum nemo."
                        },
                        new
                        {
                            Prop1 = "r9fj90gs",
                            Prop2 = "buqnp3nb",
                            OtherProp = "Delectus deleniti voluptatem id aperiam molestias dolore enim at."
                        },
                        new
                        {
                            Prop1 = "ecz1hrwd",
                            Prop2 = "qvkh0ni6",
                            OtherProp = "Rerum quis sequi velit temporibus nobis necessitatibus."
                        },
                        new
                        {
                            Prop1 = "p7tr8h9u",
                            Prop2 = "46smhh98",
                            OtherProp = "Quia atque et quasi ratione sint qui quod."
                        },
                        new
                        {
                            Prop1 = "mrtvfoe6",
                            Prop2 = "sjivmrnq",
                            OtherProp = "Reiciendis architecto sed iste non cum ipsa porro."
                        },
                        new
                        {
                            Prop1 = "25zdlgpt",
                            Prop2 = "e8bqsl8x",
                            OtherProp = "Laborum culpa minus."
                        },
                        new
                        {
                            Prop1 = "1suu4jiw",
                            Prop2 = "ekdfbkrb",
                            OtherProp = "Qui facere exercitationem consequatur necessitatibus architecto aut dolores."
                        },
                        new
                        {
                            Prop1 = "kerik1fm",
                            Prop2 = "xdtw1ux7",
                            OtherProp = "Facere et tenetur vel quia."
                        },
                        new
                        {
                            Prop1 = "qu4kpfj5",
                            Prop2 = "bmsl6x38",
                            OtherProp = "Praesentium ut et non rerum eos et."
                        },
                        new
                        {
                            Prop1 = "y2sc6r47",
                            Prop2 = "v1b5lm9t",
                            OtherProp = "Labore maxime minima velit vero magni culpa assumenda veniam."
                        },
                        new
                        {
                            Prop1 = "sc9ln94n",
                            Prop2 = "a2ni4n25",
                            OtherProp = "Quis quia quo soluta iure consequatur."
                        },
                        new
                        {
                            Prop1 = "em2byw9x",
                            Prop2 = "4okmbjij",
                            OtherProp = "Incidunt et provident labore error."
                        },
                        new
                        {
                            Prop1 = "dqhva5cz",
                            Prop2 = "fzt7e7zn",
                            OtherProp = "Tempore deserunt ea aut consectetur."
                        },
                        new
                        {
                            Prop1 = "5nla5tfs",
                            Prop2 = "ey8x7uii",
                            OtherProp = "Autem et aliquid et voluptatum."
                        },
                        new
                        {
                            Prop1 = "c5e00ghu",
                            Prop2 = "oc030xxz",
                            OtherProp = "Ipsum dolore non et enim vel eos."
                        },
                        new
                        {
                            Prop1 = "i8pmg5lg",
                            Prop2 = "sm34pnod",
                            OtherProp = "Omnis aspernatur molestiae tenetur voluptate voluptas quia voluptatibus accusamus pariatur."
                        },
                        new
                        {
                            Prop1 = "5s0vkjnw",
                            Prop2 = "q474aq8v",
                            OtherProp = "Beatae a voluptate veniam sint doloribus quam deleniti ut perferendis."
                        },
                        new
                        {
                            Prop1 = "0dl3vdyk",
                            Prop2 = "wct3f50y",
                            OtherProp = "Est qui repellat sit sit voluptas."
                        },
                        new
                        {
                            Prop1 = "dklyndi4",
                            Prop2 = "60p65c3w",
                            OtherProp = "Voluptatem culpa necessitatibus assumenda qui velit earum aliquam."
                        },
                        new
                        {
                            Prop1 = "m96h2l4x",
                            Prop2 = "p5gne2t7",
                            OtherProp = "Expedita doloremque est aliquam harum voluptates adipisci reiciendis."
                        },
                        new
                        {
                            Prop1 = "18pgl83z",
                            Prop2 = "o5zadecp",
                            OtherProp = "Praesentium qui quisquam vero ab voluptas nisi adipisci voluptas."
                        },
                        new
                        {
                            Prop1 = "8wqzo9ts",
                            Prop2 = "yn41mw56",
                            OtherProp = "Id voluptatem quisquam sit aut quibusdam porro."
                        },
                        new
                        {
                            Prop1 = "69voocjs",
                            Prop2 = "blt1mwnq",
                            OtherProp = "Incidunt voluptate laboriosam est veritatis aliquam itaque qui rem."
                        },
                        new
                        {
                            Prop1 = "khbdthe2",
                            Prop2 = "ofi5hmkd",
                            OtherProp = "Asperiores non velit expedita fugiat et."
                        },
                        new
                        {
                            Prop1 = "twxq25r5",
                            Prop2 = "a15x99ql",
                            OtherProp = "Earum rem aut ipsam impedit recusandae dolorum at voluptatem sunt."
                        },
                        new
                        {
                            Prop1 = "3kwjhdi3",
                            Prop2 = "h2bxldto",
                            OtherProp = "Omnis laboriosam laborum labore."
                        },
                        new
                        {
                            Prop1 = "2c0fjclw",
                            Prop2 = "mvin26we",
                            OtherProp = "Dolores quasi saepe minima eaque sunt ea dolorum."
                        },
                        new
                        {
                            Prop1 = "cgxrow1l",
                            Prop2 = "g72hi9zv",
                            OtherProp = "Odio quaerat eligendi dolorum debitis et et enim omnis."
                        },
                        new
                        {
                            Prop1 = "sue3y1c9",
                            Prop2 = "4a0fij9n",
                            OtherProp = "Dolorum officia ad."
                        },
                        new
                        {
                            Prop1 = "rnu9hker",
                            Prop2 = "n5z40vmq",
                            OtherProp = "Quae sit consequatur earum ex iste magni."
                        },
                        new
                        {
                            Prop1 = "1mrfw4pp",
                            Prop2 = "v7f840dl",
                            OtherProp = "Quibusdam id enim aut recusandae."
                        },
                        new
                        {
                            Prop1 = "zgsp3lsv",
                            Prop2 = "1ny4yam8",
                            OtherProp = "Autem expedita qui."
                        },
                        new
                        {
                            Prop1 = "34jhxdq5",
                            Prop2 = "9f612906",
                            OtherProp = "Vitae minima minima."
                        },
                        new
                        {
                            Prop1 = "jqhzmbyx",
                            Prop2 = "zprnkkpv",
                            OtherProp = "Autem laboriosam numquam quia veniam mollitia dicta."
                        },
                        new
                        {
                            Prop1 = "lbo0b816",
                            Prop2 = "211v62dk",
                            OtherProp = "Eum ut veniam corporis ut cum voluptatem qui voluptate sunt."
                        },
                        new
                        {
                            Prop1 = "6kqwe0hc",
                            Prop2 = "ux5pef8z",
                            OtherProp = "Cupiditate ducimus perferendis possimus officia."
                        },
                        new
                        {
                            Prop1 = "87xs10c8",
                            Prop2 = "wn2k1bjk",
                            OtherProp = "Et impedit velit ab."
                        },
                        new
                        {
                            Prop1 = "48w68t5f",
                            Prop2 = "g543pu2p",
                            OtherProp = "Debitis minus autem non enim error vero ea voluptatem a."
                        },
                        new
                        {
                            Prop1 = "yg1awpd7",
                            Prop2 = "bol7clra",
                            OtherProp = "Beatae perferendis ut qui exercitationem dolor a."
                        },
                        new
                        {
                            Prop1 = "yzgbvjx6",
                            Prop2 = "sw47axcz",
                            OtherProp = "Explicabo consequatur eligendi libero voluptatibus deleniti."
                        },
                        new
                        {
                            Prop1 = "h15a0fm6",
                            Prop2 = "cn6lanoq",
                            OtherProp = "Veritatis omnis numquam."
                        },
                        new
                        {
                            Prop1 = "g2u0bnwa",
                            Prop2 = "9g1lfd58",
                            OtherProp = "Eligendi quasi mollitia enim ea atque ea est architecto."
                        },
                        new
                        {
                            Prop1 = "guvpk3yj",
                            Prop2 = "or9tmp6e",
                            OtherProp = "Est sint ipsum officia dolores quia."
                        },
                        new
                        {
                            Prop1 = "ja6nmke5",
                            Prop2 = "5x3zyrzm",
                            OtherProp = "Perspiciatis sit mollitia voluptatum dicta soluta dolorem inventore."
                        },
                        new
                        {
                            Prop1 = "iqet3nqn",
                            Prop2 = "qbsxjti4",
                            OtherProp = "Facere voluptatem rem."
                        },
                        new
                        {
                            Prop1 = "2btux92l",
                            Prop2 = "0fvw6348",
                            OtherProp = "Nam sint dolorem quia voluptas magnam."
                        },
                        new
                        {
                            Prop1 = "q44bkh9n",
                            Prop2 = "rc1kjo6x",
                            OtherProp = "Est est sed nesciunt magni."
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
