// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using ReplaceCompositeKey;

#nullable disable

namespace ReplaceCompositeKey.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ReplaceCompositeKey.MyEntity", b =>
                {
                    b.Property<string>("Prop1")
                        .HasColumnType("text");

                    b.Property<string>("Prop2")
                        .HasColumnType("text");

                    b.Property<string>("OtherProp")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Prop1", "Prop2");

                    b.ToTable("Entities");
                });
#pragma warning restore 612, 618
        }
    }
}
